# Generated by Django 5.1.7 on 2025-03-15 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mycars',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
