# Generated by Django 5.1.7 on 2025-03-15 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0002_mycars_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mycars',
            name='date',
        ),
        migrations.AddField(
            model_name='mycars',
            name='year',
            field=models.CharField(default=2020, max_length=4),
            preserve_default=False,
        ),
    ]
