# Generated by Django 5.1.7 on 2025-03-16 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0004_mycars_created_at_mycars_description_mycars_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='mycars',
            name='category',
            field=models.ManyToManyField(related_name='car_category', to='newapp.category'),
        ),
    ]
