# Generated by Django 5.1.7 on 2025-03-24 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0005_category_mycars_category'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
